# Recommender Systems: PCA, Utility Matrix- Based


## 1.1 Import Libraries

In [2]:
import pandas as pd
import numpy as np

## 1.2 Import Data

In [3]:
#load data
data = pd.read_csv('1533148922_PBL 5 recommendation data.csv', encoding="latin-1")
data.head(5)

/Users/alisonbunce/anaconda3/envs/DeepLearning/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (20,33,73,106,158) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Customers.id Customers.fname Customers.lname Customers.company  \
0           797         Christy            Dill          Company0   
1             3            John           Smith          Company1   
2             3            John           Smith          Company1   
3             4           James        Anderson               NaN   
4             5         Abraham          Pollak          Company3   

   Customers.create_date  Customers.status  Customers.mailing  \
0             1426018724               NaN                NaN   
1             1386089139               NaN                NaN   
2             1386089139               NaN                NaN   
3             1386780263               NaN                NaN   
4             1386861599               0.0                0.0   

   Customers.reminders  Customers.tax_exempt  Customers.account_id  ...  \
0                  NaN                   NaN                   NaN  ...   
1                  NaN                   NaN                   NaN  ...   
2                  NaN                   NaN                   NaN  ...   
3                  NaN                   NaN                   NaN  ...   
4                  NaN                   NaN                   NaN  ...   

   Products.google_shopping_label  Products.product_option    Products.size  \
0                             NaN                      NaN              NaN   
1                             NaN                      NaN              NaN   
2                             NaN                      NaN  2 x Extra large   
3                             NaN                      NaN              NaN   
4                             NaN                      NaN              NaN   

   Products.material  Products.arm_style  Products.leg_style  \
0                NaN                 NaN                 NaN   
1                NaN                 NaN                 NaN   
2            Nitrile                 NaN                 NaN   
3                NaN                 NaN                 NaN   
4                NaN                 NaN                 NaN   

   Products.seat_size Products.family_id Products.saved_status  \
0                 NaN            PF61071                   0.0   
1                 NaN            PF02132                   NaN   
2                 NaN            PF00342                   0.0   
3                 NaN            PF04970                   NaN   
4                 NaN            PF03045                   NaN   

  Products.freight_cost  
0                   NaN  
1                   NaN  
2                   NaN  
3                   NaN  
4                   NaN  

[5 rows x 181 columns]

## 2. Analyze the Data

### 2.1 Create a Pivot Table

In [4]:
#create a pivot table, it shows us specifically the specifc data we want to compare
df = data.pivot_table(index=['Customers.id'], columns=['Products.name'], values='Order_Items.qty')
df.head()

Products.name  1 Box Of Medline Commode Liners with Absorbent Pad  \
Customers.id                                                        
3                                                            NaN    
4                                                            NaN    
5                                                            NaN    
7                                                            NaN    
8                                                            NaN    

Products.name  1-Ply Blockade AngelStat Surgical Gowns,Ceil Blue,Extra Large  \
Customers.id                                                                   
3                                                            NaN               
4                                                            NaN               
5                                                            NaN               
7                                                            NaN               
8                                                            NaN               

Products.name  1/2" self-adhesive hook material, 25 yard dispenser box, white  \
Customers.id                                                                    
3                                                            NaN                
4                                                            NaN                
5                                                            NaN                
7                                                            NaN                
8                                                            NaN                

Products.name  1/2" self-adhesive loop material, 25 yard dispenser box, white  \
Customers.id                                                                    
3                                                            NaN                
4                                                            NaN                
5                                                            NaN                
7                                                            NaN                
8                                                            NaN                

Products.name  100% Cotton Unisex Reversible Hyperbaric Scrub Tops,Misty Green,MZS  \
Customers.id                                                                         
3                                                            NaN                     
4                                                            NaN                     
5                                                            NaN                     
7                                                            NaN                     
8                                                            NaN                     

Products.name  100% Cotton Unisex Reversible Tops,Ceil Blue,MHS  \
Customers.id                                                      
3                                                           NaN   
4                                                           NaN   
5                                                           NaN   
7                                                           NaN   
8                                                           NaN   

Products.name  18" Hamper Stands,Standard  \
Customers.id                                
3                                     NaN   
4                                     NaN   
5                                     NaN   
7                                     NaN   
8                                     NaN   

Products.name  2" self-adhesive loop material, 10 yard dispenser box, tan  \
Customers.id                                                                
3                                                            NaN            
4                                                            NaN            
5                                                            NaN            
7                                            

Analysis note: Observe what the first customer ordered

In [5]:
#determine how many products did customer 3 order?
df.loc[3].dropna()

Products.name
SensiCare Nitrile Exam Gloves,Blue,XX-Large    1.0
Urinary Drain Bags                             4.0
Name: 3, dtype: float64

Analysis note: customer 3 bought these products and this quantity

In [6]:
#let's look back at the data we're working with to see what we need to clean
df.head()

Products.name  1 Box Of Medline Commode Liners with Absorbent Pad  \
Customers.id                                                        
3                                                            NaN    
4                                                            NaN    
5                                                            NaN    
7                                                            NaN    
8                                                            NaN    

Products.name  1-Ply Blockade AngelStat Surgical Gowns,Ceil Blue,Extra Large  \
Customers.id                                                                   
3                                                            NaN               
4                                                            NaN               
5                                                            NaN               
7                                                            NaN               
8                                                            NaN               

Products.name  1/2" self-adhesive hook material, 25 yard dispenser box, white  \
Customers.id                                                                    
3                                                            NaN                
4                                                            NaN                
5                                                            NaN                
7                                                            NaN                
8                                                            NaN                

Products.name  1/2" self-adhesive loop material, 25 yard dispenser box, white  \
Customers.id                                                                    
3                                                            NaN                
4                                                            NaN                
5                                                            NaN                
7                                                            NaN                
8                                                            NaN                

Products.name  100% Cotton Unisex Reversible Hyperbaric Scrub Tops,Misty Green,MZS  \
Customers.id                                                                         
3                                                            NaN                     
4                                                            NaN                     
5                                                            NaN                     
7                                                            NaN                     
8                                                            NaN                     

Products.name  100% Cotton Unisex Reversible Tops,Ceil Blue,MHS  \
Customers.id                                                      
3                                                           NaN   
4                                                           NaN   
5                                                           NaN   
7                                                           NaN   
8                                                           NaN   

Products.name  18" Hamper Stands,Standard  \
Customers.id                                
3                                     NaN   
4                                     NaN   
5                                     NaN   
7                                     NaN   
8                                     NaN   

Products.name  2" self-adhesive loop material, 10 yard dispenser box, tan  \
Customers.id                                                                
3                                                            NaN            
4                                                            NaN            
5                                                            NaN            
7                                            

Analysis: We have a lot of nulls, it means that the customer did not order that product so we can change the nulls to 0

## 3. Clean Data

In [8]:
#replace the null values with 0
df.fillna(0, inplace=True)

In [9]:
#double check that its done successfully
df.head()

Products.name  1 Box Of Medline Commode Liners with Absorbent Pad  \
Customers.id                                                        
3                                                            0.0    
4                                                            0.0    
5                                                            0.0    
7                                                            0.0    
8                                                            0.0    

Products.name  1-Ply Blockade AngelStat Surgical Gowns,Ceil Blue,Extra Large  \
Customers.id                                                                   
3                                                            0.0               
4                                                            0.0               
5                                                            0.0               
7                                                            0.0               
8                                                            0.0               

Products.name  1/2" self-adhesive hook material, 25 yard dispenser box, white  \
Customers.id                                                                    
3                                                            0.0                
4                                                            0.0                
5                                                            0.0                
7                                                            0.0                
8                                                            0.0                

Products.name  1/2" self-adhesive loop material, 25 yard dispenser box, white  \
Customers.id                                                                    
3                                                            0.0                
4                                                            0.0                
5                                                            0.0                
7                                                            0.0                
8                                                            0.0                

Products.name  100% Cotton Unisex Reversible Hyperbaric Scrub Tops,Misty Green,MZS  \
Customers.id                                                                         
3                                                            0.0                     
4                                                            0.0                     
5                                                            0.0                     
7                                                            0.0                     
8                                                            0.0                     

Products.name  100% Cotton Unisex Reversible Tops,Ceil Blue,MHS  \
Customers.id                                                      
3                                                           0.0   
4                                                           0.0   
5                                                           0.0   
7                                                           0.0   
8                                                           0.0   

Products.name  18" Hamper Stands,Standard  \
Customers.id                                
3                                     0.0   
4                                     0.0   
5                                     0.0   
7                                     0.0   
8                                     0.0   

Products.name  2" self-adhesive loop material, 10 yard dispenser box, tan  \
Customers.id                                                                
3                                                            0.0            
4                                                            0.0            
5                                                            0.0            
7                                            

analysis note: this is what we will use for our utility matrix

In [10]:
#double check all values still there, looks good
df.shape

(2964, 1391)

## 4. Convert our pivot table into a matrix

utility matrix now has everything filled in

now...de-mean the data (normalize by each users mean) and convert it from a dataframe to a numpy array

In [11]:
#convert the pivot table, just in a df now, into a matrix
print(df.shape)
R = df.as_matrix()
R

(2964, 1391)


/Users/alisonbunce/anaconda3/envs/DeepLearning/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

now we have a matrix we can use. lets calculate the mean for each user, and subtract the mean from each order/row (de mean the data)

## 5. Demean the Data

In [13]:
#demean the data, and show it to us for the first 5 users
import numpy as np
df_mean = np.mean(R, axis = 1)
df_mean[:5]

array([0.00359454, 0.00071891, 0.00071891, 0.00071891, 0.00071891])

In [14]:
#no columns here, just rows 
df_mean.shape

(2964,)

In [15]:
R.shape

(2964, 1391)

In [16]:
#now we subtract the mean from each element of the row

In [17]:
#remove the user matrix mean from 
# -1 keep the rows, how every many you have
# 1 i want 1 column, give me 1 column


In [18]:
#we are creating a column for each row (note in df_mean.shape shows no columns). the new column is for the mean
df_mean.reshape(-1, 1).shape

(2964, 1)

In [19]:
# take the matrix R and subtract the mean (the actual de-meaning)
R_demeaned = R - df_mean.reshape(-1,1)
R_demeaned

array([[-0.00359454, -0.00359454, -0.00359454, ..., -0.00359454,
        -0.00359454, -0.00359454],
       [-0.00071891, -0.00071891, -0.00071891, ..., -0.00071891,
        -0.00071891, -0.00071891],
       [-0.00071891, -0.00071891, -0.00071891, ..., -0.00071891,
        -0.00071891, -0.00071891],
       ...,
       [-0.00071891, -0.00071891, -0.00071891, ..., -0.00071891,
        -0.00071891, -0.00071891],
       [-0.00071891, -0.00071891, -0.00071891, ..., -0.00071891,
        -0.00071891, -0.00071891],
       [-0.00143781, -0.00143781, -0.00143781, ..., -0.00143781,
        -0.00143781, -0.00143781]])

In [20]:
#double check that we have the same # of rows and columns as we did in the orig matrix R, but these are all demeaned
R_demeaned.shape

(2964, 1391)

## 6. Singular Value Decompostion

Use SVD to convert the one big matrix R_demeaned, into 3 smaller matrixes

In [21]:
from scipy.sparse.linalg import svds

#u is the customer id  matrix, which is all the users
# R is the utility matrix
# v transpose is the product matrix (can be whatver you want ot call it)
# sigmna is diagonal matrix, is a sqaure matrix that only has values diagonal (has all 0s aside from the values that fall diagonally in the matrix) 
#ask zia about diag matrix***

U, sigma, Vt = svds(R_demeaned, k = 200)
#take those 1391 columns and compress them into 20 (changed to 200)

In [35]:
#this is just showing us what we did about (not required)
svds(R_demeaned, k=200)

(array([[-4.05357911e-04,  9.40043623e-04, -3.00457761e-03, ...,
          8.88817182e-05,  5.41193183e-05,  3.26840685e-05],
        [-5.33178499e-04,  1.80634689e-03, -6.26593590e-02, ...,
          1.76622882e-05,  1.07983447e-05,  6.53118755e-06],
        [ 5.75344381e-05, -1.30405969e-04,  3.96044654e-04, ...,
          1.75754672e-05,  1.07787900e-05,  6.52686582e-06],
        ...,
        [ 5.75344381e-05, -1.30405969e-04,  3.96044654e-04, ...,
          1.75754672e-05,  1.07787900e-05,  6.52686582e-06],
        [-1.60351318e-04,  3.77486398e-04, -1.25017778e-03, ...,
          1.77279333e-05,  1.08130544e-05,  6.53443238e-06],
        [ 1.88091499e-04, -4.23682661e-04,  1.26983361e-03, ...,
          3.52375214e-05,  2.15771153e-05,  1.30580518e-05]]),
 array([  3.36202179,   3.3771842 ,   3.41055862,   3.45300264,
          3.46160618,   3.46308891,   3.46410162,   3.46410162,
          3.46706591,   3.49477894,   3.49815052,   3.56881898,
          3.57347766,   3.59589397,  

recall that we now have 3 matrixes, 
1. U
2. Sigma
3. Vt

Double check our new matrixes, note that this breaks down every product

In [23]:
#len is always rows
#shape will give you the columns and rows
print(U.shape)

(2964, 200)


In [24]:
#check to see the matrix
U

array([[ 4.05357911e-04,  9.40043623e-04, -3.00457761e-03, ...,
        -8.88817182e-05, -5.41193183e-05,  3.26840685e-05],
       [ 5.33178499e-04,  1.80634689e-03, -6.26593590e-02, ...,
        -1.76622882e-05, -1.07983447e-05,  6.53118755e-06],
       [-5.75344381e-05, -1.30405969e-04,  3.96044654e-04, ...,
        -1.75754672e-05, -1.07787900e-05,  6.52686582e-06],
       ...,
       [-5.75344381e-05, -1.30405969e-04,  3.96044654e-04, ...,
        -1.75754672e-05, -1.07787900e-05,  6.52686582e-06],
       [ 1.60351318e-04,  3.77486398e-04, -1.25017778e-03, ...,
        -1.77279333e-05, -1.08130544e-05,  6.53443238e-06],
       [-1.88091499e-04, -4.23682661e-04,  1.26983361e-03, ...,
        -3.52375214e-05, -2.15771153e-05,  1.30580518e-05]])

In [25]:
#when you do svd, sigma comes back as an array,not a matrix, you have to convert it 
print(sigma.shape)
sigma

(200,)


array([  3.36202179,   3.3771842 ,   3.41055862,   3.45300264,
         3.46160618,   3.46308891,   3.46410162,   3.46410162,
         3.46706591,   3.49477894,   3.49815052,   3.56881898,
         3.57347766,   3.59589397,   3.60555128,   3.60555128,
         3.60555128,   3.60555128,   3.60555128,   3.6180361 ,
         3.63701791,   3.64005494,   3.65379173,   3.66434611,
         3.66723664,   3.69232563,   3.69847672,   3.73888739,
         3.7415709 ,   3.75082966,   3.76312753,   3.76603563,
         3.7740417 ,   3.78872917,   3.85951662,   3.87154822,
         3.88434172,   3.90017852,   3.90816085,   3.9249627 ,
         3.98073487,   4.        ,   4.        ,   4.        ,
         4.        ,   4.        ,   4.        ,   4.        ,
         4.        ,   4.        ,   4.        ,   4.        ,
         4.00842046,   4.01495341,   4.02388876,   4.05840434,
         4.10341775,   4.1181487 ,   4.12310563,   4.12310563,
         4.12310563,   4.12310563,   4.12310563,   4.13

In [26]:
#this breaks out every single product
print(Vt.shape)
Vt

(200, 1391)


array([[-0.00027289, -0.00019343, -0.00021422, ..., -0.00019343,
        -0.00021422, -0.00021422],
       [-0.00061882, -0.0004404 , -0.00048723, ..., -0.0004404 ,
        -0.00048723, -0.00048723],
       [ 0.00188169,  0.00135073,  0.00149097, ...,  0.00135073,
         0.00149097,  0.00149097],
       ...,
       [-0.00071064, -0.00070933, -0.00070976, ..., -0.00070933,
        -0.00070976, -0.00070976],
       [-0.00071702, -0.00071653, -0.0007167 , ..., -0.00071653,
        -0.0007167 , -0.0007167 ],
       [ 0.00071788,  0.0007177 ,  0.00071776, ...,  0.0007177 ,
         0.00071776,  0.00071776]])

In [27]:
#convert array output into diagonal matrix
sigma = np.diag(sigma)
sigma

array([[  3.36202179,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   3.3771842 ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   3.41055862, ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ...,  40.35895071,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
         66.47618489,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , 109.96053694]])

In [28]:
#we took the sigma, just 20 columns, and converted it into diag matrix successfully 20x20, this confirms that
sigma.shape

(200, 200)

#we changed the nulls, converted into into 3 matries, now we have 3 matrizes, now take these 3 u,daig sign, 
do a dot product, of these 3 matrixes to come up with a predicted matrix.

through the use of that is linear algebra, we will be multiply these togther to give us a predicted utility matrix. this will have predicted product quantities


attributing diagnoal values. same number of rows and columns. when you get the result, multiply it by v transpose, not multiplication, its matrix multiplication

In [29]:
#np.dop is the function for matix multiplication
predicted_products = np.dot(np.dot(U, sigma), Vt)
predicted_products

array([[-3.65726739e-03, -2.90445397e-03, -3.12099219e-03, ...,
        -2.90445397e-03, -3.12099219e-03, -3.12099219e-03],
       [ 1.80571050e-05,  4.96734693e-05,  4.24026841e-05, ...,
         4.96734693e-05,  4.24026841e-05,  4.24026841e-05],
       [ 1.65860571e-04,  1.43740766e-04,  1.50107541e-04, ...,
         1.43740766e-04,  1.50107541e-04,  1.50107541e-04],
       ...,
       [ 1.65860571e-04,  1.43740766e-04,  1.50107541e-04, ...,
         1.43740766e-04,  1.50107541e-04,  1.50107541e-04],
       [-6.67329068e-04, -4.88788431e-04, -5.37934275e-04, ...,
        -4.88788431e-04, -5.37934275e-04, -5.37934275e-04],
       [ 4.11900082e-04,  3.51765878e-04,  3.68949476e-04, ...,
         3.51765878e-04,  3.68949476e-04,  3.68949476e-04]])

Now...based on all these predicted ratings, we convert this into a dataframe. bring all the columns from the pivot table and assign them as columns

## 7. Create a new Dataframe with our predictions

In [30]:
new_df = pd.DataFrame(predicted_products, columns=df.columns)
new_df.head(2)

Products.name  1 Box Of Medline Commode Liners with Absorbent Pad  \
0                                                      -0.003657    
1                                                       0.000018    

Products.name  1-Ply Blockade AngelStat Surgical Gowns,Ceil Blue,Extra Large  \
0                                                      -0.002904               
1                                                       0.000050               

Products.name  1/2" self-adhesive hook material, 25 yard dispenser box, white  \
0                                                      -0.003121                
1                                                       0.000042                

Products.name  1/2" self-adhesive loop material, 25 yard dispenser box, white  \
0                                                      -0.003121                
1                                                       0.000042                

Products.name  100% Cotton Unisex Reversible Hyperbaric Scrub Tops,Misty Green,MZS  \
0                                                      -0.003819                     
1                                                       0.000009                     

Products.name  100% Cotton Unisex Reversible Tops,Ceil Blue,MHS  \
0                                                     -0.004767   
1                                                     -0.001576   

Products.name  18" Hamper Stands,Standard  \
0                               -0.003764   
1                               -0.000933   

Products.name  2" self-adhesive loop material, 10 yard dispenser box, tan  \
0                                                      -0.002904            
1                                                       0.000050            

Products.name  2" self-adhesive loop material, 25 yard dispenser box, tan  \
0                                                      -0.002904            
1                                                       0.000050            

Products.name  2-Ply Tissue/Poly Professional Towels,Not Applicable  ...  \
0                                                      -0.003595     ...   
1                                                      -0.000719     ...   

Products.name  Wrist and Forearm Splint with Abducted Thumb,Large  \
0                                                      -0.003657    
1                                                       0.000018    

Products.name  Wrist and Forearm Splint with Abducted Thumb,Medium  \
0                                                      -0.003620     
1                                                       0.000022     

Products.name  Wrist and Forearm Splint with Abducted Thumb,Small  \
0                                                      -0.003153    
1                                                       0.000040    

Products.name  Wrist and Forearm Splints,Medium  \
0                                     -0.005385   
1                                     -0.000111   

Products.name  Youth Two-Button Folding Walkers with 5" Wheels,5"  \
0                                                      -0.003395    
1                                                      -0.000002    

Products.name  Youth-Sized Walker Platform Attachment  \
0                                           -0.002904   
1                                            0.000050   

Products.name  Zip-Style Biohazard Specimen Bags,Clear  \
0                                            -0.002904   
1                                             0.000050   

Products.name  iWalker Euro Style Rollator  \
0                                -0.002904   
1                                 0.000050   

Products.name  sEMG - MyoTrac Home Trainer with Myoscan Active Sensor and extender cable, 1-channel  \
0                                                      -0.003121                                      
1                                                       0.000042                            

These are our predictions! 

In [31]:
#first users prediction for every product (foucsing on first user)

#we are matching up the values vs predicted values for one particular user
new_df.loc[0].sort_values(ascending=False)
#the algo svd tells us that based on other users and other products, this is most likely what user will buy next. 
#amaz would rec these 3 items first becuase you bouht them last time... based on you as a user

Products.name
Urinary Drain Bags                                                      4.006971
SensiCare Nitrile Exam Gloves,Blue,XX-Large                             0.890972
UltraFlex Male External Catheters,Medium                                0.220565
Walker Flip Tray                                                       -0.000660
Protection Plus Super Protective Adult Underwear,2X-Large              -0.001969
                                                                          ...   
Full Body Patient Lift Sling                                           -0.010051
Ultra-Soft Disposable Dry Cleansing Cloth,White,10"X13"                -0.010657
Soothe & Cool No Rinse Shampoo & Body Wash,8.00 OZ                     -0.010742
Remedy Olivamine Foaming Body Cleanser - 9 ounce - Pack of 3 bottles   -0.011651
Dycem&reg; non-slip rectangular pad, 10"x14", blue                     -0.012746
Name: 0, Length: 1391, dtype: float64

In [32]:
#show the orignial df, note that 3 is the first index in the orig df 
#the actual list of what he has bought, numbers signifiy quanity of purchased items
df.loc[3].sort_values(ascending=False)

Products.name
Urinary Drain Bags                                                             4.0
SensiCare Nitrile Exam Gloves,Blue,XX-Large                                    1.0
Dynarex 3596, Athletic Tape, 1&frac12;" x 15 yds., 4/8/Cs                      0.0
Dynarex 3672, Triangular Bandage 36x36x51 - 12/Bx                              0.0
Dynarex 4234, Stool Container - Polystyrene    100/cs                          0.0
                                                                              ... 
Premium Knit Incontinence Underpants,X-Large                                   0.0
Premium Plastic Raised Toilet Seat with Lock and Padded Armrests, Elongated    0.0
Premium Seat Riser with Removable Arms                                         0.0
Premium Series Shower Chair with Back and Arms                                 0.0
1 Box Of Medline Commode Liners with Absorbent Pad                             0.0
Name: 3, Length: 1391, dtype: float64

In [37]:
new_df.loc[0].sort_values(ascending=False)[:20]

Products.name
Urinary Drain Bags                                                                   4.006971
SensiCare Nitrile Exam Gloves,Blue,XX-Large                                          0.890972
UltraFlex Male External Catheters,Medium                                             0.220565
Walker Flip Tray                                                                    -0.000660
Protection Plus Super Protective Adult Underwear,2X-Large                           -0.001969
Fresh Wave Continuous Release Gel,8.000 OZ                                          -0.002025
FitRight Ultra Briefs,32"-42"                                                       -0.002166
SmartStep SS2515BLK, Smooth, Non-Slip Top; Non-Skid Bottom                          -0.002417
Four-Panel Abdominal Binders,Large/X-Large                                          -0.002522
Stool Softener                                                                      -0.002523
Bathroom Safety Shower Tub Bench Chair        

Analysis note: note that we predicted the correct recommendation for Customer #1(index 3 in df) for the first 2 products. We then provided the next best possible recommendations based on what customer 3 had already bought and what other customers had bought (this came from our orig dataset) 